---
title: "Make tables"
author: "Frank Edwards"
format: docx
---

```{r include = F}
library(tidyverse)
library(knitr)
# read descriptive tables
child_bin <- read_csv("./output/child_period_bin.csv")
child_freq <- read_csv("./output/child_period_freq.csv")
hh_bin <- read_csv("./output/hh_period_bin.csv")
hh_freq <- read_csv("./output/hh_period_freq.csv")
# read regression tables
r_main <- read_csv("./vis/reg_table_main.csv")
```

# Table 1

```{r echo = F, message = F}
# table 1 inputs ----------------------------------------------------------
group <- read_csv("./data/group_assignment.csv")

datw1 <- read_csv("./data/w1_reduced.csv") |>
  left_join(group) |>
  rename(GROUP = Group) |>
  mutate(GROUP = ifelse(is.na(GROUP), "C", GROUP))

temp0 <- datw1 |>
  group_by(GROUP, County) |>
  count()

temp1 <- datw1 |>
  group_by(GROUP) |>
  summarize(n_child_mn = mean(n_child), 
            n_child_sd = sd(n_child),
            Age_mn = mean(Age_c),
            Age_sd = sd(Age_c),
            GenderF = sum(Gender_s == "Female", na.rm = T),
            GenderF_pct = mean(Gender_s == "Female", na.rm = T) * 100) 

abstract <- datw1 |>
  summarize(n_child_mn = mean(n_child), 
            n_child_sd = sd(n_child),
            Age_mn = mean(Age_c),
            Age_sd = sd(Age_c),
            GenderF = sum(Gender_s == "Female", na.rm = T),
            GenderF_pct = mean(Gender_s == "Female", na.rm = T) * 100) 

temp2 <- datw1 |>
  group_by(GROUP) |>
  summarize(across(Race_White:Race_Other, sum, na.rm = T))

# edu levels for table, less than HS, HS or GED, some college
# levels: 
abs <- datw1 |>
  summarize(LessThanHS = mean(Edu<5, na.rm=T),
            HS = mean((Edu==5) | (Edu==6), na.rm=T),
            College = mean(Edu>6, na.rm=T))
temp4 <- datw1 |>
  group_by(GROUP) |>
  summarize(
    LessThanHS = sum(Edu<5, na.rm=T),
    HS = sum((Edu==5) | (Edu==6), na.rm=T),
    College = sum(Edu>6, na.rm=T))

tab_out <- temp1 |> 
  left_join(temp2) |> 
  left_join(temp4) |> 
  pivot_longer(n_child_mn:College) |> 
  pivot_wider(names_from = GROUP)

temp0 <- temp0 |> 
  pivot_wider(names_from = GROUP, values_from = n) |> 
  rename(name = County)

tab_out <-tab_out |> 
  rename(Treatment = "T", Control = "C") |> 
  select(name, Treatment, Control) |> 
  mutate(Treatment = round(Treatment, 2),
         Control = round(Control, 2)) |> 
  mutate(trt_pct = round(Treatment / 150 * 100, 2),
         ctrl_pct = round(Control / 265 * 100, 2)) |> 
  mutate(Trt = paste(Treatment, trt_pct, sep = ", "),
         Ctrl = paste(Control, ctrl_pct, sep = ", ")) |> 
  select(name, Trt, Ctrl)

kable(tab_out)
```

# Table 2

```{r echo = F, message = F}
# just do observed for table 2. imputations are shown in fig 2
bin_tab <- child_bin |> 
  filter(.imp==0) 

bin_tab_pct <- bin_tab |> 
  mutate(across(TotalCPS_bin:Prev_bin, \(x) round(x/n_child * 100, 1)))

tab_out <- bin_tab
for(i in 1:nrow(tab_out)){
  tab_out$TotalCPS_bin[i] <- paste(tab_out$TotalCPS_bin[i], " (", bin_tab_pct$TotalCPS_bin[i], "%)",sep = "")
  tab_out$Confirmed_bin[i] <- paste(tab_out$Confirmed_bin[i], " (", bin_tab_pct$Confirmed_bin[i], "%)",sep = "")
  tab_out$Prev_bin[i] <- paste(tab_out$Prev_bin[i], " (", bin_tab_pct$Prev_bin[i], "%)",sep = "")
  tab_out$FC_bin[i] <- paste(tab_out$FC_bin[i], " (", bin_tab_pct$FC_bin[i], "%)",sep = "")
  }

tab_out <- tab_out |> 
  select(GROUP, Wave, TotalCPS_bin, Confirmed_bin, Prev_bin, FC_bin) |> 
  pivot_longer(TotalCPS_bin:FC_bin) |> 
  pivot_wider(names_from = GROUP, values_from = value) |> 
  select(Wave, name, T, C) |> 
  arrange(name, Wave)

kable(tab_out)
```

# Table 3

```{r echo = F, message = F}
tab_out <- r_main |> 
  select(variable, Parameter, OR, OR_low, OR_high, q) |> 
  mutate(across(OR:q, \(x) round(x, 2))) 

tab_out$int <- NA
for(i in 1:nrow(tab_out)){
  tab_out$int[i] <- paste(tab_out$OR[i], " [", tab_out$OR_low[i], ", ", tab_out$OR_high[i], "]", sep = "")
}

kable(tab_out |> 
        select(variable, Parameter, int, q))
```
